/// Generated by AssetsRefGenerator on 2021/08/07
class Res {
  static const String dice1 = "images/dice1.png";
  static const String dice2 = "images/dice2.png";
  static const String dice3 = "images/dice3.png";
  static const String dice4 = "images/dice4.png";
  static const String dice5 = "images/dice5.png";
  static const String dice6 = "images/dice6.png";
}
